### PR TITLE
Only for test - DO NOT MERGE

### PR DESCRIPTION
**Pull request by vishwassp-hcl-intel**
Signed-off-by: Vishwas SP <vishwasx.s.premachandra@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Sandbox Testing
Test Links :

### CODE REVIEW

**Comment by vishwassp-hcl-intel** [comment]
recheck

**Comment by vishwassp-hcl-intel** [comment]
recheck

**Comment by ernestojeda** [comment]
recheck

**Comment by ernestojeda** [comment]
Will it work with recheck

**Comment by soda480** [comment]
recheck

**Comment by soda480** [comment]
recheck

**Comment by soda480** [comment]
recheck

**Comment by ernestojeda** [comment]
salkfjasl;dkjfals;dlrrecheckasdajldjasld**^4$$@

**Comment by ernestojeda** [comment]
récheck

**Comment by ernestojeda** [comment]
brecheck

**Comment by ernestojeda** [comment]
réćhéćk

**Comment by ernestojeda** [comment]
recheck for fun

**Comment by ernestojeda** [comment]
I wish I could recheck this PR

**Comment by vishwassp-hcl-intel** [comment]
recheck

**Pull request closed without merging**
